import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { ExternalNavigation } from "./Navbar";
import Footer from "@/components/Footer";


const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${outfit.className} antialiased`}>
        <header>
          <ExternalNavigation/>
        </header>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
